### ISSUE TITLE
Add validation options to mdc-select and mdc-switch

### ISSUE THREAD

**Issue by JWScheijgrond** [arjendeblok/aurelia-material-skeleton#2]
Currently it is not possible to validate the MDC-Select and MDC-Switch if they are filled correctly.

**Comment by arjendeblok** [comment]
Implemented in branch **new-validation**. Please check if it works as expected.
Please note that there are interface changes for **mdc-text-field**, **mdc-switch** and **mdc-select**.
So please read the documentation about the new interface.

**Comment by arjendeblok** [comment]
Merged into master.
